# Generated by Django 5.2.8 on 2025-11-06 00:03

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProyecto',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='modified at')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('cliente', models.CharField(max_length=200)),
                ('sistema_coordenadas', models.CharField(choices=[('WGS84', 'WGS84 (GPS)'), ('UTM', 'Universal Transverse Mercator'), ('LOCAL', 'Sistema Local')], default='UTM', max_length=10)),
                ('zona_utm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('hemisferio', models.CharField(blank=True, choices=[('N', 'Norte'), ('S', 'Sur')], max_length=1, null=True)),
                ('lat_referencia', models.FloatField(help_text='Latitud del punto de referencia')),
                ('lon_referencia', models.FloatField(help_text='Longitud del punto de referencia')),
                ('elevacion_referencia', models.FloatField(default=0, help_text='Elevación sobre nivel del mar (m)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLAN', 'Planificación'), ('EJECUCION', 'En Ejecución'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='PLAN', max_length=20)),
                ('presupuesto_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('director_obra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('residente_obra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Proyecto',
                'verbose_name_plural': 'historical Proyectos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cliente', models.CharField(max_length=200)),
                ('sistema_coordenadas', models.CharField(choices=[('WGS84', 'WGS84 (GPS)'), ('UTM', 'Universal Transverse Mercator'), ('LOCAL', 'Sistema Local')], default='UTM', max_length=10)),
                ('zona_utm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('hemisferio', models.CharField(blank=True, choices=[('N', 'Norte'), ('S', 'Sur')], max_length=1, null=True)),
                ('lat_referencia', models.FloatField(help_text='Latitud del punto de referencia')),
                ('lon_referencia', models.FloatField(help_text='Longitud del punto de referencia')),
                ('elevacion_referencia', models.FloatField(default=0, help_text='Elevación sobre nivel del mar (m)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLAN', 'Planificación'), ('EJECUCION', 'En Ejecución'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='PLAN', max_length=20)),
                ('presupuesto_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('director_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_dirigidos', to=settings.AUTH_USER_MODEL)),
                ('residente_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_residencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
