# Generated by Django 5.2.8 on 2025-11-06 01:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproyecto',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ElementoConstructivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ZAPATA', 'Zapata'), ('COLUMNA', 'Columna'), ('TRABE', 'Trabe/Viga'), ('MURO', 'Muro'), ('LOSA', 'Losa'), ('CIMENTACION', 'Cimentación'), ('PAVIMENTO', 'Pavimento'), ('TERRACERIA', 'Terracería'), ('DRENAJE', 'Drenaje'), ('OTRO', 'Otro')], max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('elevacion', models.FloatField(help_text='Elevación en metros')),
                ('utm_este', models.FloatField(blank=True, null=True)),
                ('utm_norte', models.FloatField(blank=True, null=True)),
                ('utm_zona', models.IntegerField(blank=True, null=True)),
                ('area_proyecto', models.FloatField(blank=True, help_text='Área en m²', null=True)),
                ('volumen_proyecto', models.FloatField(blank=True, help_text='Volumen en m³', null=True)),
                ('longitud_proyecto', models.FloatField(blank=True, help_text='Longitud en m', null=True)),
                ('porcentaje_avance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REPLANTEO', 'En Replanteo'), ('EXCAVACION', 'Excavación'), ('CIMBRADO', 'Cimbrado'), ('ARMADO', 'Armado de Acero'), ('COLADO', 'Colado'), ('TERMINADO', 'Terminado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio_programada', models.DateField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_programada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='gestor.proyecto')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento Constructivo',
                'verbose_name_plural': 'Elementos Constructivos',
                'ordering': ['codigo'],
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
    ]
