# Generated by Django 5.2.8 on 2025-11-06 02:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_alter_historicalproyecto_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud_actual', models.FloatField(blank=True, null=True)),
                ('longitud_actual', models.FloatField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('elemento_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_trabajando', to='gestor.elementoconstructivo')),
                ('jefe_cuadrilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='gestor.proyecto')),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
            },
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_punto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('BENCHMARK', 'Banco de Nivel'), ('REPLANTEO', 'Punto de Replanteo'), ('VERIFICACION', 'Verificación'), ('CONTROL', 'Control de Calidad'), ('LEVANTAMIENTO', 'Levantamiento')], max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('elevacion', models.FloatField()),
                ('precision_horizontal', models.FloatField(blank=True, help_text='Precisión horizontal en cm', null=True)),
                ('precision_vertical', models.FloatField(blank=True, help_text='Precisión vertical en cm', null=True)),
                ('equipo_medicion', models.CharField(choices=[('GPS_DIFERENCIAL', 'GPS Diferencial'), ('GPS_RTK', 'GPS RTK'), ('ESTACION_TOTAL', 'Estación Total'), ('NIVEL', 'Nivel Óptico'), ('GPS_MOVIL', 'GPS Móvil')], max_length=30)),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('elemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puntos_control', to='gestor.elementoconstructivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_control', to='gestor.proyecto')),
                ('topografo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Control',
                'verbose_name_plural': 'Puntos de Control',
                'ordering': ['-fecha_medicion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteAvance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('avance_cantidad', models.FloatField(help_text='Cantidad ejecutada en la unidad del concepto')),
                ('avance_porcentaje', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes_avance/')),
                ('descripcion', models.TextField()),
                ('materiales_utilizados', models.TextField(blank=True)),
                ('personal_asignado', models.IntegerField(default=0)),
                ('horas_trabajadas', models.FloatField(default=0)),
                ('validado', models.BooleanField(default=False)),
                ('cuadrilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='gestor.cuadrilla')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='gestor.elementoconstructivo')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Avance',
                'verbose_name_plural': 'Reportes de Avance',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='VolumenTerraceria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('area_m2', models.FloatField()),
                ('volumen_corte_m3', models.FloatField(default=0)),
                ('volumen_relleno_m3', models.FloatField(default=0)),
                ('volumen_neto_m3', models.FloatField(default=0)),
                ('metodo_calculo', models.CharField(choices=[('SECCIONES', 'Áreas de Secciones'), ('GRID', 'Retícula (Grid)'), ('TIN', 'Triangulación (TIN)'), ('CURVAS', 'Curvas de Nivel')], max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('archivo_levantamiento', models.FileField(blank=True, help_text='Archivo CSV con coordenadas del levantamiento', null=True, upload_to='levantamientos/')),
                ('calculado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumenes', to='gestor.proyecto')),
            ],
            options={
                'verbose_name': 'Volumen de Terracería',
                'verbose_name_plural': 'Volúmenes de Terracería',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
