# Generated by Django 5.2.8 on 2026-06-29 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_cuadrilla_puntocontrol_reporteavance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadrilla',
            options={'ordering': ['-estado', 'nombre'], 'verbose_name': 'Cuadrilla', 'verbose_name_plural': 'Cuadrillas'},
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='jefe_cuadrilla',
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='latitud_actual',
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='longitud_actual',
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='ultima_actualizacion',
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='especialidad',
            field=models.CharField(choices=[('TOPOGRAFIA', 'Topografía'), ('TERRACERIA', 'Terracería y Maquinaria'), ('ALBANILERIA', 'Albañilería'), ('FIERREROS', 'Acero / Fierreros'), ('CARPINTEROS', 'Carpintería / Cimbra'), ('GENERAL', 'Ayudantes Generales')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa (En Campo)'), ('INACTIVA', 'Inactiva (Desarticulada)'), ('DESCANSO', 'En Descanso / Pausa')], default='ACTIVA', max_length=15),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_lideradas', to=settings.AUTH_USER_MODEL, verbose_name='Líder / Cabo'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='cuadrillas', to=settings.AUTH_USER_MODEL, verbose_name='Integrantes Operativos'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='elemento_actual',
            field=models.ForeignKey(blank=True, help_text='Elemento constructivo en el que están trabajando en este momento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_asignadas', to='gestor.elementoconstructivo', verbose_name='Actividad Actual (Frente de Trabajo)'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='nombre',
            field=models.CharField(help_text='Ej: Cuadrilla Alfa - Fierreros', max_length=100),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='gestor.proyecto', verbose_name='Proyecto Asignado'),
        ),
    ]
