# Generated by Django 5.2.8 on 2026-07-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_alter_cuadrilla_options_remove_cuadrilla_activa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('especialidad', models.CharField(help_text='Ej: Topógrafo, Operador, Peón', max_length=100)),
                ('cuadrilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='gestor.cuadrilla')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tarea', models.TextField(help_text='Descripción exacta de la labor asignada')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud GPS', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud GPS', max_digits=9, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Programada'), (2, 'En Tránsito'), (3, 'Pausada por Clima/Material'), (4, 'En Ejecución'), (5, 'Finalizada')], default=1)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_diarias', to='gestor.cuadrilla')),
                ('punto_control', models.ForeignKey(help_text='Frente de trabajo o cadenamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.puntocontrol')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestor.participante')),
            ],
        ),
    ]
