# Generated by Django 5.2.8 on 2026-07-19 20:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_participante_actividadparticipante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del material (ej. Cemento Cruz Azul)', max_length=200, unique=True)),
                ('unidad_medida', models.CharField(help_text='Ej. bulto, ton, m3, pza, litro', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='reporteavance',
            name='materiales_utilizados',
        ),
        migrations.CreateModel(
            name='InventarioProyecto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_total_ingresado', models.FloatField(default=0, help_text='Cantidad total de material que ha entrado al proyecto', validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_disponible', models.FloatField(default=0, help_text='Cantidad actual disponible en el proyecto')),
                ('costo_unitario_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario referencial para presupuestos', max_digits=10, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_materiales', to='gestor.proyecto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='gestor.material')),
            ],
            options={
                'verbose_name': 'Inventario de Proyecto',
                'verbose_name_plural': 'Inventarios de Proyectos',
                'ordering': ['proyecto__codigo', 'material__nombre'],
                'unique_together': {('proyecto', 'material')},
            },
        ),
        migrations.CreateModel(
            name='MaterialUtilizado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_utilizada', models.FloatField(help_text='Cantidad consumida en la unidad de medida del material', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el uso de este material')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestor.inventarioproyecto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_utilizados_rel', to='gestor.reporteavance')),
            ],
            options={
                'verbose_name': 'Material Utilizado',
                'verbose_name_plural': 'Materiales Utilizados',
                'ordering': ['-created_at'],
            },
        ),
    ]
