# Generated by Django 5.2.8 on 2026-07-19 20:53

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_material_remove_reporteavance_materiales_utilizados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPresupuesto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(help_text='Ej. CIM-001', max_length=50)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(help_text='Ej. m2, m3, pza, kg', max_length=20)),
                ('cantidad_contratada', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_contratado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_presupuesto', to='gestor.proyecto')),
            ],
            options={
                'verbose_name': 'Concepto de Presupuesto',
                'verbose_name_plural': 'Conceptos de Presupuesto',
                'ordering': ['proyecto', 'clave'],
                'unique_together': {('proyecto', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalConceptoPresupuesto',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('clave', models.CharField(help_text='Ej. CIM-001', max_length=50)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(help_text='Ej. m2, m3, pza, kg', max_length=20)),
                ('cantidad_contratada', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_contratado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestor.proyecto')),
            ],
            options={
                'verbose_name': 'historical Concepto de Presupuesto',
                'verbose_name_plural': 'historical Conceptos de Presupuesto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NumeroGenerador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_ejecutada', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_medicion', models.DateField(help_text='Fecha real en que se realizó la medición física')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_generadores', to='gestor.conceptopresupuesto')),
                ('reporte_avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_generadores', to='gestor.reporteavance')),
            ],
            options={
                'verbose_name': 'Número Generador',
                'verbose_name_plural': 'Números Generadores',
                'ordering': ['-fecha_medicion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElementoConceptoRelacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_asignada', models.DecimalField(decimal_places=4, help_text='Cantidad del concepto asignada a este elemento', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_relacionados', to='gestor.conceptopresupuesto')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_asignados', to='gestor.elementoconstructivo')),
            ],
            options={
                'verbose_name': 'Relación Elemento-Concepto',
                'verbose_name_plural': 'Relaciones Elementos-Conceptos',
                'unique_together': {('elemento', 'concepto')},
            },
        ),
    ]
