# Generated by Django 5.2.8 on 2026-07-19 21:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_conceptopresupuesto_historicalconceptopresupuesto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(help_text='Consecutivo de la estimación (1, 2, 3...)')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('AUTORIZADA', 'Autorizada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('autorizada_por', models.ForeignKey(blank=True, help_text='Usuario con rol para autorizar la estimación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimaciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimaciones', to='gestor.proyecto')),
            ],
            options={
                'verbose_name': 'Estimación',
                'verbose_name_plural': 'Estimaciones',
                'ordering': ['proyecto', 'numero'],
                'unique_together': {('proyecto', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='EstimacionDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_periodo', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_periodo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('acumulado_anterior', models.DecimalField(decimal_places=4, default=0, help_text='Cantidad acumulada hasta la estimación anterior', max_digits=14)),
                ('acumulado_actual', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Cantidad acumulada incluyendo este periodo', max_digits=14)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_estimaciones', to='gestor.conceptopresupuesto')),
                ('estimacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestor.estimacion')),
            ],
            options={
                'verbose_name': 'Detalle de Estimación',
                'verbose_name_plural': 'Detalles de Estimación',
                'ordering': ['estimacion', 'concepto__clave'],
                'unique_together': {('estimacion', 'concepto')},
            },
        ),
    ]
