# Generated by Django 5.2.8 on 2026-07-19 21:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_estimacion_estimaciondetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenioModificatorio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_convenio', models.CharField(help_text='Ej. CM-01', max_length=50)),
                ('fecha_firma', models.DateField()),
                ('ampliacion_monto', models.DecimalField(decimal_places=2, default=0, help_text='Importe adicional autorizado (puede ser negativo si es deductiva)', max_digits=16)),
                ('ampliacion_dias', models.IntegerField(default=0, help_text='Días adicionales otorgados al plazo de ejecución')),
                ('motivo', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='gestor.proyecto')),
            ],
            options={
                'verbose_name': 'Convenio Modificatorio',
                'verbose_name_plural': 'Convenios Modificatorios',
                'ordering': ['proyecto', 'fecha_firma'],
            },
        ),
        migrations.CreateModel(
            name='GastoReal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('MANO_OBRA', 'Mano de Obra'), ('MAQUINARIA', 'Maquinaria y Equipo'), ('SUBCONTRATO', 'Subcontrato'), ('INDIRECTO', 'Indirecto')], default='MATERIAL', max_length=50)),
                ('fecha_gasto', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('factura', models.CharField(blank=True, max_length=100)),
                ('concepto', models.ForeignKey(blank=True, help_text='Opcional. Para asociar el gasto directamente a un concepto específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_reales', to='gestor.conceptopresupuesto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_reales', to='gestor.proyecto')),
            ],
            options={
                'verbose_name': 'Gasto Real',
                'verbose_name_plural': 'Gastos Reales',
                'ordering': ['-fecha_gasto'],
            },
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FONDO_GARANTIA', 'Fondo de Garantía (5%)'), ('AMORTIZACION_ANTICIPO', 'Amortización de Anticipo'), ('OTRO', 'Otro')], default='FONDO_GARANTIA', max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='gestor.estimacion')),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
                'ordering': ['estimacion', 'tipo'],
            },
        ),
    ]
